### ISSUE TITLE
Failed to build TSOAX 'eigen3/Eigen/Dense':No such file or directory

### ISSUE THREAD

**Issue by RyumaSuper** [tix209/TSOAX#4]
Hi,
Now I'm building TSOAX on Windows then I got an error.
I couldn't open include file in util.h. 'eigen3/Eigen/Dense':No such file or directory
I already add the eigen3 path in Include path as you mention.

![キャプチャ](https://github.com/tix209/TSOAX/assets/116268430/a4f52ad5-05a5-40c9-84e8-64dcdd186312)
![キャプチャ2](https://github.com/tix209/TSOAX/assets/116268430/596b0cad-32ab-45c1-9a4d-fc867a071776)
![キャプチャ3](https://github.com/tix209/TSOAX/assets/116268430/82b3def9-1111-435a-80de-cd6e9e67efd6)

**Comment by vavylonis** [comment]
Can you try changing 'eigen3/Eigen/Dense' to the specific path in your system?

**Comment by RyumaSuper** [comment]
Thanks for the reply.
Actually, this error has already been resolved.
Probably it was caused by a mistake in the environment variable when building with cmake.
If you don't mind, I would be glad to solve #5.
