### ISSUE TITLE
"undefined reference" errors during "make"

### ISSUE THREAD

**Issue by hanhongqing** [tix209/TSOAX#7]
Hi!

I used conda to install Eigen, Qt, VTK (from "conda-forge" channel) in a Linux environment. After some easier issues, and simplifying the package (any file not needed by "batch_tsoax.cc" are removed), now I face the following errors during "make":
1. CMakeFiles/Project.dir/multisnake.o: in function `soax::Multisnake::Multisnake()':
multisnake.cc:(): undefined reference to `vtable for soax::Multisnake'
2. CMakeFiles/Project.dir/multisnake.o: in function `soax::Multisnake::~Multisnake()':
multisnake.cc:(): undefined reference to `vtable for soax::Multisnake'
3. CMakeFiles/Project.dir/multisnake.o: in function `soax::Multisnake::Evolve()':
multisnake.cc:(): undefined reference to `soax::Multisnake::ExtractionProgressed(int)'
4. /Scrt1.o: in function `_start': undefined reference to `main'

While the complete version has only one additional error which appeared 56 times in various classes:
5. "undefined reference to `soax::SOME_GUI_CLASS::staticMetaObject'".

Wondering if you could give some suggestions. Thanks.

**Comment by vavylonis** [comment]
We haven't this error before.  Could it be related to https://stackoverflow.com/questions/3065154/undefined-reference-to-vtable 
We can try to replicate or perhaps you can contact me to discuss on zoom/email.

**Comment by hanhongqing** [comment]
> We haven't this error before. Could it be related to https://stackoverflow.com/questions/3065154/undefined-reference-to-vtable We can try to replicate or perhaps you can contact me to discuss on zoom/email.

Thank you very much for your response. I looked at the answers but I'm unsure I have the expertise to find the right answer. So yes if you could replicate the errors that will be extremely helpful. I'll write an email to you with the modified package and conda environment.
